[project]
name = "happydamsel"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "pyyaml>=6.0.3",
]

[dependency-groups]
dev = [
    "mypy>=1.19.1",
    "pytest>=8.0",
    "pytest-asyncio>=1.3.0",
    "ruff>=0.14.10",
    "types-pyyaml>=6.0.12.20250915",
]

[project.scripts]
happydamsel = "damsel.cli:main"


[tool.ruff]
# Максимальная длина строки (можно сделать как в Black)
line-length = 94
src = ["./damsel"]


[tool.mypy]
python_version = "3.13"
strict = true
warn_unused_ignores = true
disallow_untyped_defs = true
mypy_path = "damsel"
ignore_missing_imports = true
show_error_codes = true
